// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function escapeSql(value) {
  return value.replace(/'/g, "''");
}

function escapeHtml(value) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#x27;");
}

function escapeJs(value) {
  return value.replace(/\\\\/g, "\\\\").replace(/\"/g, "\\\"").replace(/'/g, "\\'").replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
}

function toCodePoints(str) {
  let length = str.length;
  if (length === 0) {
    return {
      TAG: "Ok",
      _0: []
    };
  }
  let codes = Belt_Array.make(length, 0);
  let valid = true;
  let errorIdx = 0;
  for (let i = 0; i < length; ++i) {
    if (valid) {
      let code = str.charCodeAt(i) | 0;
      if (code > 255) {
        valid = false;
        errorIdx = i;
      } else {
        codes[i] = code;
      }
    }
  }
  if (valid) {
    return {
      TAG: "Ok",
      _0: codes
    };
  } else {
    return {
      TAG: "Error",
      _0: `Character at position ` + String(errorIdx) + ` is outside ASCII range`
    };
  }
}

function fromCodePoints(codes) {
  let length = codes.length;
  if (length === 0) {
    return {
      TAG: "Ok",
      _0: ""
    };
  }
  let valid = true;
  let errorIdx = 0;
  let result = "";
  for (let i = 0; i < length; ++i) {
    if (valid) {
      let code = codes[i];
      if (code < 0 || code > 65535) {
        valid = false;
        errorIdx = i;
      } else {
        result = result + String.fromCharCode(code);
      }
    }
  }
  if (valid) {
    return {
      TAG: "Ok",
      _0: result
    };
  } else {
    return {
      TAG: "Error",
      _0: `Invalid code point at position ` + String(errorIdx)
    };
  }
}

function isAscii(str) {
  let length = str.length;
  let valid = true;
  for (let i = 0; i < length; ++i) {
    if (valid) {
      let code = str.charCodeAt(i) | 0;
      if (code > 127) {
        valid = false;
      }
    }
  }
  return valid;
}

function isPrintableAscii(str) {
  let length = str.length;
  let valid = true;
  for (let i = 0; i < length; ++i) {
    if (valid) {
      let code = str.charCodeAt(i) | 0;
      if (code < 32 || code > 126) {
        valid = false;
      }
    }
  }
  return valid;
}

export {
  escapeSql,
  escapeHtml,
  escapeJs,
  toCodePoints,
  fromCodePoints,
  isAscii,
  isPrintableAscii,
}
/* No side effect */
