// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

function div(numerator, denominator) {
  if (denominator === 0) {
    return;
  } else {
    return Primitive_int.div(numerator, denominator);
  }
}

function divOr($$default, numerator, denominator) {
  let v = div(numerator, denominator);
  if (v !== undefined) {
    return v;
  } else {
    return $$default;
  }
}

function safeMod(numerator, denominator) {
  if (denominator === 0) {
    return;
  } else {
    return Primitive_int.mod_(numerator, denominator);
  }
}

function addChecked(a, b) {
  let result = a + b | 0;
  if (a > 0 && b > 0 && result < 0 || a < 0 && b < 0 && result > 0) {
    return;
  } else {
    return result;
  }
}

function subChecked(a, b) {
  let result = a - b | 0;
  if (a > 0 && b < 0 && result < 0 || a < 0 && b > 0 && result > 0) {
    return;
  } else {
    return result;
  }
}

function mulChecked(a, b) {
  if (a === 0 || b === 0) {
    return 0;
  }
  let result = a * b | 0;
  if (Primitive_int.div(result, a) !== b) {
    return;
  } else {
    return result;
  }
}

function absSafe(n) {
  if (n === Pervasives.min_int) {
    return;
  } else if (n < 0) {
    return -n | 0;
  } else {
    return n;
  }
}

function clamp(lo, hi, value) {
  if (value < lo) {
    return lo;
  } else if (value > hi) {
    return hi;
  } else {
    return value;
  }
}

function powChecked(base, exp) {
  if (exp < 0) {
    return;
  }
  if (exp === 0) {
    return 1;
  }
  if (exp === 1) {
    return base;
  }
  let half = powChecked(base, exp / 2 | 0);
  if (half === undefined) {
    return;
  }
  let squared = mulChecked(half, half);
  if (squared !== undefined) {
    if (exp % 2 === 0) {
      return squared;
    } else {
      return mulChecked(squared, base);
    }
  }
}

function percentOf(percent, total) {
  let product = mulChecked(percent, total);
  if (product !== undefined) {
    return div(product, 100);
  }
}

function asPercent(part, whole) {
  let scaled = mulChecked(part, 100);
  if (scaled !== undefined) {
    return div(scaled, whole);
  }
}

function inRange(value, lo, hi) {
  if (value >= lo) {
    return value <= hi;
  } else {
    return false;
  }
}

function inRangeExcluding(value, lo, hi, excluded) {
  if (inRange(value, lo, hi)) {
    return !Belt_Array.some(excluded, e => e === value);
  } else {
    return false;
  }
}

function fromString(str) {
  let trimmed = str.trim();
  if (trimmed.length === 0) {
    return;
  }
  let isValid = /^-?\\d+$/.test(trimmed);
  if (isValid) {
    return Belt_Int.fromString(trimmed);
  }
}

function fromStringInRange(str, lo, hi) {
  let value = fromString(str);
  if (value !== undefined && inRange(value, lo, hi)) {
    return value;
  }
}

export {
  div,
  divOr,
  safeMod,
  addChecked,
  subChecked,
  mulChecked,
  absSafe,
  clamp,
  powChecked,
  percentOf,
  asPercent,
  inRange,
  inRangeExcluding,
  fromString,
  fromStringInRange,
}
/* No side effect */
