// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function hasTraversal(path) {
  if (path.includes("..") || path.includes("~")) {
    return true;
  } else if (path.startsWith("/")) {
    return path.includes("..");
  } else {
    return false;
  }
}

function isSafe(path) {
  return !hasTraversal(path);
}

function sanitizeFilename(filename) {
  return filename.replace(/\\.\\./g, "_").replace(/[\\/\\\\]/g, "_").replace(/[\\x00-\\x1f]/g, "").replace(/[<>:\"\\|\\?\\*]/g, "_");
}

function safeJoin(base, parts) {
  let hasUnsafe = Belt_Array.some(parts, hasTraversal);
  if (hasUnsafe) {
    return;
  }
  let result = {
    contents: base
  };
  Belt_Array.forEach(parts, part => {
    let sanitized = sanitizeFilename(part);
    let base = result.contents;
    if (base.endsWith("/")) {
      result.contents = base + sanitized;
    } else {
      result.contents = base + "/" + sanitized;
    }
  });
  return result.contents;
}

export {
  hasTraversal,
  isSafe,
  sanitizeFilename,
  safeJoin,
}
/* No side effect */
