// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Core from "@tauri-apps/api/core";
import * as PluginFs from "@tauri-apps/plugin-fs";
import * as PluginDialog from "@tauri-apps/plugin-dialog";

function isGossamerRuntime() {
  return typeof window !== 'undefined'
    && typeof window.__gossamer_invoke === 'function';
}
;

function gossamerInvoke(cmd, args) {
  return window.__gossamer_invoke(cmd, args);
}
;

function isTauriRuntime() {
  return typeof window !== 'undefined'
    && window.__TAURI_INTERNALS__ != null
    && !window.__TAURI_INTERNALS__.__BROWSER_SHIM__;
}
;

var _detectedRuntime = null;
function detectRuntime() {
  if (_detectedRuntime !== null) return _detectedRuntime;
  if (typeof window !== 'undefined' && typeof window.__gossamer_invoke === 'function') {
    _detectedRuntime = 'gossamer';
  } else if (typeof window !== 'undefined' && window.__TAURI_INTERNALS__ != null && !window.__TAURI_INTERNALS__.__BROWSER_SHIM__) {
    _detectedRuntime = 'tauri';
  } else {
    _detectedRuntime = 'browser';
  }
  return _detectedRuntime;
}
;

function detectRuntime() {
  let match = globalThis.detectRuntime();
  switch (match) {
    case "gossamer" :
      return "Gossamer";
    case "tauri" :
      return "Tauri";
    default:
      return "BrowserOnly";
  }
}

function invoke(cmd, args) {
  if (isGossamerRuntime()) {
    return gossamerInvoke(cmd, args);
  } else if (isTauriRuntime()) {
    return Core.invoke(cmd, args);
  } else {
    return Promise.reject(Stdlib_JsError.throwWithMessage(`No desktop runtime — "` + cmd + `" requires Gossamer or Tauri`));
  }
}

function hasDesktopRuntime() {
  if (isGossamerRuntime()) {
    return true;
  } else {
    return isTauriRuntime();
  }
}

function runtimeName() {
  let match = detectRuntime();
  switch (match) {
    case "Gossamer" :
      return "Gossamer";
    case "Tauri" :
      return "Tauri";
    case "BrowserOnly" :
      return "Browser";
  }
}

function open(opts) {
  if (isGossamerRuntime()) {
    return gossamerInvoke("__gossamer_dialog_open", opts);
  } else if (isTauriRuntime()) {
    return PluginDialog.open(opts);
  } else {
    return Promise.reject(Stdlib_JsError.throwWithMessage("No desktop runtime — file dialogs require Gossamer or Tauri"));
  }
}

function save(opts) {
  if (isGossamerRuntime()) {
    return gossamerInvoke("__gossamer_dialog_save", opts);
  } else if (isTauriRuntime()) {
    return PluginDialog.save(opts);
  } else {
    return Promise.reject(Stdlib_JsError.throwWithMessage("No desktop runtime — save dialogs require Gossamer or Tauri"));
  }
}

let Dialog = {
  open: open,
  save: save
};

function readTextFile(path) {
  if (isGossamerRuntime()) {
    return gossamerInvoke("__gossamer_fs_read_text", {
      path: path
    });
  } else if (isTauriRuntime()) {
    return PluginFs.readTextFile(path);
  } else {
    return Promise.reject(Stdlib_JsError.throwWithMessage("No desktop runtime — filesystem access requires Gossamer or Tauri"));
  }
}

function writeTextFile(path, contents) {
  if (isGossamerRuntime()) {
    return gossamerInvoke("__gossamer_fs_write_text", {
      path: path,
      contents: contents
    });
  } else if (isTauriRuntime()) {
    return PluginFs.writeTextFile(path, contents);
  } else {
    return Promise.reject(Stdlib_JsError.throwWithMessage("No desktop runtime — filesystem access requires Gossamer or Tauri"));
  }
}

let Fs = {
  readTextFile: readTextFile,
  writeTextFile: writeTextFile
};

export {
  detectRuntime,
  invoke,
  hasDesktopRuntime,
  runtimeName,
  Dialog,
  Fs,
}
/*  Not a pure module */
