// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Proven_SafeMath from "./proven/Proven_SafeMath.res.js";

let forbiddenBytes = [
  160,
  194
];

function isValidByte(byte) {
  return Proven_SafeMath.inRangeExcluding(byte, 0, 127, forbiddenBytes);
}

function describeInvalidByte(byte) {
  if (byte === 160) {
    return "NBSP (Non-Breaking Space)";
  } else if (byte === 194) {
    return "UTF-8 continuation marker";
  } else if (byte > 127) {
    return `Non-ASCII (> 127)`;
  } else if (byte < 0) {
    return "Negative value";
  } else {
    return "Unknown";
  }
}

let Constraints = {
  maxByte: 127,
  forbiddenNbsp: 160,
  forbiddenUtf8: 194,
  forbiddenBytes: forbiddenBytes,
  isValidByte: isValidByte,
  describeInvalidByte: describeInvalidByte
};

export {
  Constraints,
}
/* No side effect */
